name:                assign1
version:             1.0.0
github:              "VictorWinberg/edan40/assign1"
license:             BSD3
author:              "Victor Winberg and Emma Asklund"

dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src

executables:
  assign1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assign1

tests:
  assign1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assign1
    - HUnit
